# This is a basic workflow to help you get started with Actions

name: Daily CDN Update

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'

  push:
    branches: master
  
  pull_request:
    branches: master
      
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update-site:
    name: Update CDN content
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo
        uses: actions/checkout@v4.0.0

      - name: Run Script
        run: sudo chmod +x ./scripts/main.sh && sudo ./scripts/main.sh

      - name: Preparing commit title
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      
      - name: Add & Commit to repo
        uses: EndBug/add-and-commit@v9.1.3
        with:
          cwd: './'
          default_author: github_actions
          message: ${{ steps.date.outputs.date }}
          tag: ${{ steps.date.outputs.date }}